"""Added summary to DocumentAnalysis

Revision ID: 1d3585d2ab58
Revises: 4ecb8c53b8fe
Create Date: 2024-05-05 06:32:11.276060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d3585d2ab58'
down_revision = '4ecb8c53b8fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_analysis', 'sentiment',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_analysis', 'sentiment',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
