"""Added keywords to DocumentAnalysis

Revision ID: 4aed4df00665
Revises: 1d3585d2ab58
Create Date: 2024-05-05 18:31:22.449766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aed4df00665'
down_revision = '1d3585d2ab58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_analysis', sa.Column('keywords', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_analysis', 'keywords')
    # ### end Alembic commands ###
